
FROM ubuntu:14.04

MAINTAINER prithviraj6116@gmail.com

RUN /bin/bash -c "apt-get -y update;apt-get -y upgrade; apt-get -y install git python"

RUN /bin/bash -c "git clone https://github.com/noxrepo/pox.git"






